# Generated by Django 4.2.30 on 2026-08-17 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='如 v1.0', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', '开放'), ('locked', '锁定'), ('archived', '归档')], default='open', max_length=16)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_baseline', models.BooleanField(default=False, help_text='是否基线版本')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.project')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='如 2024Q1Sprint3', max_length=128)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', '计划中'), ('active', '进行中'), ('closed', '已结束')], default='planning', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='projects.project')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iterations', to='releases.version')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
