# Generated by Django 4.2.30 on 2026-08-17 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requirements', '__first__'),
        ('releases', '__first__'),
        ('projects', '0001_initial'),
        ('actionwords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('case_id', models.CharField(help_text='用例编号,如 SHOP-001', max_length=64, unique=True)),
                ('type', models.CharField(choices=[('api', 'API'), ('ui', 'UI')], default='api', max_length=8)),
                ('priority', models.IntegerField(choices=[(1, 'P0'), (2, 'P1'), (3, 'P2'), (4, 'P3')], default=2)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '就绪'), ('deprecated', '废弃')], default='draft', max_length=16)),
                ('tags', models.CharField(blank=True, help_text='逗号分隔', max_length=256)),
                ('precondition', models.TextField(blank=True)),
                ('expected', models.TextField(blank=True)),
                ('iteration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='releases.iteration')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='projects.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='projects.project')),
                ('requirements', models.ManyToManyField(blank=True, related_name='cases', to='requirements.requirement')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='releases.version')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('setup', '前置步骤'), ('test', '测试步骤'), ('teardown', '后置步骤')], default='test', max_length=16)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, help_text='步骤名,留空用 AW 名', max_length=256)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, help_text='步骤备注')),
                ('action_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_steps', to='actionwords.actionword')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='testcases.testcase')),
            ],
            options={
                'ordering': ['section', 'order', 'id'],
                'unique_together': {('test_case', 'section', 'order')},
            },
        ),
    ]
