# Generated by Django 4.2.30 on 2026-08-17 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='AW 名称,如 创建订单', max_length=128)),
                ('key', models.CharField(help_text='唯一 key,如 createOrder', max_length=128)),
                ('category', models.CharField(blank=True, help_text='分组,如 订单/用户', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('openapi', 'OpenAPI 解析'), ('manual', '手动创建')], default='manual', max_length=16)),
                ('suggested_section', models.CharField(choices=[('any', '任意'), ('setup', '前置'), ('test', '测试'), ('teardown', '后置')], default='any', help_text='建议放置的步骤区', max_length=16)),
                ('endpoint', models.CharField(blank=True, help_text='如 /orders/{id}', max_length=256)),
                ('method', models.CharField(blank=True, help_text='GET/POST/...', max_length=8)),
                ('code_template', models.TextField(blank=True, help_text='Jinja2 模板,渲染后是该 AW 在用例函数体里的一行/多行 Python 代码')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='参数 schema,{"properties":{...},"required":[...]}')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_words', to='projects.project')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('project', 'key')},
            },
        ),
    ]
