# Generated by Django 4.2.30 on 2026-08-17 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('file_path', models.CharField(help_text='相对仓库根的路径', max_length=512, unique=True)),
                ('type', models.CharField(choices=[('api', 'API'), ('ui', 'UI')], default='api', max_length=8)),
                ('content', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='projects.project')),
                ('test_case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script', to='testcases.testcase')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
