# Generated by Django 4.2.30 on 2026-08-17 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('ext_key', models.CharField(blank=True, help_text='外部系统编号,如 JIRA-1234', max_length=64)),
                ('ext_url', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, help_text='jira/zentao/local', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='open', max_length=32)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.project')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('project', 'ext_key')},
            },
        ),
    ]
