# Generated by Django 4.2.30 on 2026-08-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenkins_job_name', models.CharField(blank=True, max_length=128)),
                ('jenkins_queue_id', models.IntegerField(blank=True, null=True)),
                ('jenkins_build_number', models.IntegerField(blank=True, null=True)),
                ('jenkins_build_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('aborted', '已取消'), ('error', '异常')], default='queued', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('trigger', models.CharField(choices=[('manual', '手动'), ('cron', '定时'), ('webhook', 'Webhook')], default='manual', max_length=16)),
                ('cron_expr', models.CharField(blank=True, help_text='5字段 cron,如 0 2 * * *', max_length=64)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '归档')], default='draft', max_length=16)),
                ('jenkins_job_name', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('cases', models.ManyToManyField(related_name='tasks', to='testcases.testcase')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
