# Generated by Django 4.2.30 on 2026-08-17 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='如 dev/staging/prod', max_length=64, unique=True)),
                ('api_base_url', models.CharField(max_length=512)),
                ('ui_base_url', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(blank=True, help_text='完整路径,如 /shop/order', max_length=512)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='variables.variablecategory')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_categories', to='projects.project')),
            ],
            options={
                'ordering': ['path', 'name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('global', '全局'), ('project', '项目'), ('env', '环境')], default='project', max_length=16)),
                ('key', models.CharField(max_length=128)),
                ('value', models.TextField(blank=True, help_text='静态值或动态表达式')),
                ('type', models.CharField(choices=[('string', 'string'), ('int', 'int'), ('bool', 'bool'), ('json', 'json')], default='string', max_length=8)),
                ('description', models.TextField(blank=True, help_text='备注')),
                ('is_secret', models.BooleanField(default=False, help_text='保护:API 返回 ***')),
                ('is_encrypted', models.BooleanField(default=False, help_text='加密:Fernet 存储级加密')),
                ('is_dynamic', models.BooleanField(default=False, help_text='动态:value 是表达式,运行时计算')),
                ('dynamic_expr', models.TextField(blank=True, help_text="动态表达式,如 datetime.now().strftime('%Y%m%d')")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables', to='variables.variablecategory')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='variables.environment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='projects.project')),
            ],
            options={
                'ordering': ['scope', 'key'],
                'unique_together': {('scope', 'project', 'environment', 'key')},
            },
        ),
    ]
